version: '2.1'
orbs:
  gh: circleci/github-cli@2.0
  node: circleci/node@4.3
workflows:
  test-and-deploy:
    jobs:
      - node/test
      - gh/release:
          context:
            - GITHUB_CREDS
          filters:
            branches:
              only:
                - master
          notes-file: changelog.md
          requires:
            - node/test
          tag: 1.0.0
          title: The initial release

